name: Bug
description: Report a bug
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Steps to reproduce, expected vs actual
    validations:
      required: true
